function y = cnmfe_lowpassfilter_4hz_20db(x,fs)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 21-Jun-2016 21:44:26

% persistent Hd;
% 
% if isempty(Hd)
% 
%     Fpass = 3;    % Passband Frequency
%     Fstop = 4;  % Stopband Frequency
%     Apass = 1;    % Passband Ripple (dB)
%     Astop = 100;  % Stopband Attenuation (dB)
%     Fs    = fs;   % Sampling Frequency
% 
%     h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
% 
%     Hd = design(h, 'equiripple', ...
%         'MinOrder', 'any', ...
%         'StopbandShape', 'flat');
% 
% 
% 
% %     set(Hd,'PersistentMemory',true);
% 
% end
% keyboard();
% y = filtfilt(Hd,Hd,x);


persistent d
if isempty(d)
    d = designfilt('lowpassfir', ...
        'PassbandFrequency',3/fs,'StopbandFrequency',4/fs, ...
        'PassbandRipple',1,'StopbandAttenuation',40, ...
        'DesignMethod','equiripple','SampleRate',fs);
end
    y = filtfilt(d,x);
end

